#!/bin/sh

#######################################
# WLNet VPN Connector Tool
# Last Updated: 2012-12-20
#######################################

# The network providing the same resources as the VPN.
PRIVATE_NETWORK_UUID='030b4744-9fb2-4af9-abae-baf0ebe8d745'

LOW_SECURITY_VPN_NAME='WLNet Networks (Tacoma)'
MAX_SECURITY_VPN_NAME='WLNet Networks (Tacoma) [Secure]'

# Prevent recursive VPN connections.
if [ $2 = 'vpn-up' ]; then 
    exit 0
fi

if [ $(nmcli con status | grep $PRIVATE_NETWORK_UUID -c) -eq 1 ]; then
    echo "Connected to WLNet network, VPN not needed"
    exit 0
fi

if [ $(nmcli con status | grep 'p1p1       ' -c) -ne 0 ]; then
    if [ $(nmcli con status | egrep "${LOW_SECURITY_VPN_NAME}") ]; then
        exit 0
    fi

    echo "Connecting to low security VPN"
    nmcli con up id "${LOW_SECURITY_VPN_NAME}"
    exit 0
fi

if [ $(nmcli con status | grep "${MAX_SECURITY_VPN_NAME}") ]; then
    exit 0
fi

echo "Connecting to high security VPN"
nmcli con up id "${MAX_SECURITY_VPN_NAME}"
exit
