#!/bin/sh

#######################################
# WLNet VPN Connector Tool
# Last Updated: 2013-01-23
#######################################


# The network providing the same resources as the VPN.
PRIVATE_NETWORK_UUID=''
GOOD_SECURITY_NETWORK_UUID=''

# --- The VPN networks to connect to. ---

# The VPN that only provides access to local resources.
LOW_SECURITY_VPN_UUID=''
# The VPN that redirects all traffic
MAX_SECURITY_VPN_UUID=''

INTERFACE=$1
OPERATION=$2

# Prevent recursive VPN connections.
if [ $OPERATION = 'vpn-up' -o $OPERATION = 'vpn-down' ]; then 
    exit 0
fi

if [ $OPERATION = 'down' -a $(nmcli con status | grep "$GOOD_SECURITY_NETWORK_UUID" -c) -eq 0 ]; then
    nmcli nm wifi on
fi

if [ $(nmcli con status | grep "$PRIVATE_NETWORK_UUID" -c) -eq 1 ]; then
    echo "Connected to private network, VPN not needed"
    nmcli nm wifi off
    nmcli con down uuid "${MAX_SECURITY_VPN_UUID}"
    nmcli con down uuid "${LOW_SECURITY_VPN_UUID}"
    exit 0
fi

if [ $(nmcli con status | grep "$GOOD_SECURITY_NETWORK_UUID" -c) -ne 0 ]; then
    echo "On wired network"
    # We are connected to a wired network.
    nmcli nm wifi off

    if [ $(nmcli con status | grep "${LOW_SECURITY_VPN_UUID}" -c) -eq 0 ]; then
        echo "Connecting to low security VPN"
        nmcli con up uuid "${LOW_SECURITY_VPN_UUID}"
        exit 0
    fi
fi

# We are connected to a wireless network. Connect to the VPN if not alreay connected.
if [ $(nmcli con status | grep "${MAX_SECURITY_VPN_UUID}" -c) -eq 1 ]; then
    exit 0
fi

echo "Connecting to high security VPN"
nmcli con up uuid "${MAX_SECURITY_VPN_UUID}"

exit 0
